INSERT INTO "Agencies" VALUES (1, 'United States Army Corps of Engineering', 'U.S. Army Corps of Engineers has responded to changing defense requirements and played an integral part in the development of the country.', 'USACE', '2018-12-10 17:26:00.437032');
INSERT INTO "Agencies" VALUES (2, 'United States Geological Survey', 'The USGS provide science about the natural hazards that threaten lives and livelihoods; the water, energy, minerals, and other natural resources we rely on; the health of our ecosystems and environment; and the impacts of climate and land-use change.', 'USGS', '2018-12-10 17:26:00.632397');
INSERT INTO "DamageTypes" VALUES (1, 'Flooding', 'Damaged due to flood', NULL);
INSERT INTO "DamageTypes" VALUES (2, 'Infrastructure', 'Structure or building damage', NULL);
INSERT INTO "DamageTypes" VALUES (3, 'Mortality', 'Death', NULL);
INSERT INTO "DamageTypes" VALUES (4, 'Property', 'Property damage', NULL);
INSERT INTO "DamageTypes" VALUES (5, 'Other', 'Other - see description/comments', NULL);
INSERT INTO "FileTypes" VALUES (1, 'Image', 'Photograph');
INSERT INTO "FileTypes" VALUES (2, 'Doc', 'Data sheet or text document.');
INSERT INTO "FileTypes" VALUES (3, 'Pub', 'Publication file.');
INSERT INTO "FileTypes" VALUES (4, 'Other', 'Other document type not listed.');
INSERT INTO "IceConditionTypes" VALUES (1, 'Decay', 'Ice decaying.');
INSERT INTO "IceConditionTypes" VALUES (2, 'Melting-Snow', 'Snow showing signs of melting.');
INSERT INTO "IceConditionTypes" VALUES (3, 'Melting-Ice', 'Ice showing signs of melting.');
INSERT INTO "IceConditionTypes" VALUES (4, 'Candled', 'Ice showing signs of candling.');
INSERT INTO "IceConditionTypes" VALUES (5, 'Crack', 'Ice showing signs of cracking.');
INSERT INTO "IceConditionTypes" VALUES (6, 'Fracture', 'Ice showing signs of candling.');
INSERT INTO "IceConditionTypes" VALUES (7, 'Breakup', 'Ice showing signs of breakup.');
INSERT INTO "JamTypes" VALUES (1, 'Freezeup', '', NULL);
INSERT INTO "JamTypes" VALUES (2, 'Aufeis', '', NULL);
INSERT INTO "JamTypes" VALUES (3, 'Anchor Ice', '', NULL);
INSERT INTO "JamTypes" VALUES (4, 'Breakup', '', NULL);
INSERT INTO "JamTypes" VALUES (5, 'Combination', '', NULL);
INSERT INTO "JamTypes" VALUES (6, 'Released', '', NULL);
INSERT INTO "JamTypes" VALUES (7, 'Closure', '', NULL);
INSERT INTO "JamTypes" VALUES (8, 'Uknown', '', NULL);
INSERT INTO "RiverConditionTypes" VALUES (1, 'Bankfull', '');
INSERT INTO "RiverConditionTypes" VALUES (2, 'Flooding', '');
INSERT INTO "Roles" VALUES (1, 'Administrator', 'System Administrator', '2018-12-10 17:33:01.50626');
INSERT INTO "Roles" VALUES (2, 'Internal', 'Internal Event Observer', '2018-12-10 21:59:51.901879');
INSERT INTO "Roles" VALUES (3, 'External', 'External Event Observer (default)', '2018-12-10 21:59:57.66349');
INSERT INTO "RoughnessTypes" VALUES (1, 'Smooth', 'Smooth surface roughness');
INSERT INTO "RoughnessTypes" VALUES (2, '< 0.5 ft.', '');
INSERT INTO "RoughnessTypes" VALUES (3, '< 1.0 ft.', '');
INSERT INTO "RoughnessTypes" VALUES (4, '< 1.5 ft.', '');
INSERT INTO "RoughnessTypes" VALUES (5, '> 1.5 ft.', '');
INSERT INTO "StageTypes" VALUES (1, 'Drop down', 'Drop down messurment from known location.');
INSERT INTO "StageTypes" VALUES (2, 'Gage reading', '');
INSERT INTO "WeatherConditionTypes" VALUES (1, 'Water Temerature (F)', '');
INSERT INTO "WeatherConditionTypes" VALUES (2, 'Air Temperature (F)', '');
INSERT INTO "WeatherConditionTypes" VALUES (3, 'Rain (in.)', '');
INSERT INTO "WeatherConditionTypes" VALUES (4, 'Snow depth (in.)', '');
INSERT INTO "WeatherConditionTypes" VALUES (5, 'Average Wind speed (mph)', '');
INSERT INTO "WeatherConditionTypes" VALUES (6, 'Wind Direction', '');
